// <auto-generated />
using System;
using CyberNexus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyberNexus.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.3")
                        .HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CyberNexus.Api.Models.Achievement", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Key").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("TitleEn").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("TitleAr").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("DescriptionEn").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("DescriptionAr").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<int>("XpReward").HasColumnType("integer");
                b.Property<int>("RequiredLevel").HasColumnType("integer");
                b.Property<string>("IconKey").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.HasKey("Id");
                b.HasIndex("Key").IsUnique();
                b.ToTable("Achievements");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.AppUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<int>("Xp").HasColumnType("integer");
                b.Property<int>("Level").HasColumnType("integer");
                b.Property<int>("CurrentStreak").HasColumnType("integer");
                b.Property<DateTime?>("LastActivityDate").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.LearningPath", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("TitleEn").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("TitleAr").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("DescriptionEn").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("DescriptionAr").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<int>("Order").HasColumnType("integer");
                b.HasKey("Id");
                b.ToTable("LearningPaths");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.Course", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("TitleEn").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("TitleAr").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("DescriptionEn").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("DescriptionAr").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<int>("Order").HasColumnType("integer");
                b.Property<int>("LearningPathId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("LearningPathId");
                b.ToTable("Courses");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.Lesson", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("TitleEn").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("TitleAr").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("ContentEn").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<string>("ContentAr").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<int>("Order").HasColumnType("integer");
                b.Property<int>("XpReward").HasColumnType("integer");
                b.Property<int>("CourseId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("CourseId");
                b.ToTable("Lessons");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.Quiz", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("TitleEn").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("TitleAr").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<int>("PassingScore").HasColumnType("integer");
                b.Property<int>("XpReward").HasColumnType("integer");
                b.Property<int?>("CourseId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("CourseId");
                b.ToTable("Quizzes");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.QuizQuestion", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("QuizId").HasColumnType("integer");
                b.Property<string>("QuestionEn").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("QuestionAr").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("Options").IsRequired().HasColumnType("text");
                b.Property<int>("CorrectIndex").HasColumnType("integer");
                b.Property<string>("ExplanationEn").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("ExplanationAr").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<int>("Order").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("QuizId");
                b.ToTable("QuizQuestions");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.Challenge", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("TitleEn").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("TitleAr").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("DescriptionEn").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<string>("DescriptionAr").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<string>("Difficulty").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<int>("XpReward").HasColumnType("integer");
                b.Property<int>("RequiredLevel").HasColumnType("integer");
                b.Property<int>("Order").HasColumnType("integer");
                b.Property<int>("CorrectIndex").HasColumnType("integer");
                b.Property<string>("Options").IsRequired().HasColumnType("text");
                b.Property<string>("ExplanationEn").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("ExplanationAr").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<int>("EstimatedMinutes").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("Order");
                b.ToTable("Challenges");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.UserLessonProgress", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("UserId").HasColumnType("integer");
                b.Property<int>("LessonId").HasColumnType("integer");
                b.Property<DateTime>("CompletedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("UserId", "LessonId").IsUnique();
                b.ToTable("UserLessonProgresses");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.UserChallengeResult", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("UserId").HasColumnType("integer");
                b.Property<int>("ChallengeId").HasColumnType("integer");
                b.Property<int>("AnswerIndex").HasColumnType("integer");
                b.Property<bool>("IsCorrect").HasColumnType("boolean");
                b.Property<DateTime>("SolvedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("UserId", "ChallengeId").IsUnique();
                b.ToTable("UserChallengeResults");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.UserAchievement", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("UserId").HasColumnType("integer");
                b.Property<int>("AchievementId").HasColumnType("integer");
                b.Property<DateTime>("UnlockedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("UserId", "AchievementId").IsUnique();
                b.ToTable("UserAchievements");
            });

            modelBuilder.Entity("CyberNexus.Api.Models.UserQuizAttempt", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("UserId").HasColumnType("integer");
                b.Property<int>("QuizId").HasColumnType("integer");
                b.Property<int>("Score").HasColumnType("integer");
                b.Property<bool>("Passed").HasColumnType("boolean");
                b.Property<DateTime>("AttemptedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("UserId", "QuizId");
                b.ToTable("UserQuizAttempts");
            });
#pragma warning restore 612, 618
        }
    }
}
